export const ADMIN_ROUTE = {
  LOGIN: '/admin/login',
  DASHBOARD: '/admin/dashboard',
  PAGES: '/admin/pages',
  PRODUCTS: '/admin/products',
  PRODUCT_NEW: '/admin/products/new',
  NOTICES_AND_NEWS: '/admin/notices-and-news',
  FOREX_RATES: '/admin/forex-rates',
  MENU_ITEMS: '/admin/menu-items',
  FORMS: '/admin/forms',
  ASSETS: '/admin/assets',
  FOOTER: '/admin/footer',
  LOCATIONS: '/admin/locations',
  TOOLS: '/admin/tools',
  EMI_CALCULATOR: '/admin/tools/emi-calculator',
  FD_CALCULATOR: '/admin/tools/fd-calculator',
  ELIGIBILITY_CHECKER: '/admin/tools/eligibility-checker',
  CARD_GROUPS: '/admin/card-groups',
};
