import type { SelectFieldOption } from '@/components/ui/inputs/SelectField';
import type { ForexColumn, ForexRate } from '../_types/forex';

export const forexPublishedDate = '04/09/2026';

export const forexUpdatedAt = '2026-09-04 10:10:02';

export const forexColumns: ForexColumn[] = [
  { key: 'name', label: 'Currency', width: 'w-[368px]' },
  { key: 'unit', label: 'Unit', width: 'w-[113px]' },
  {
    key: 'cashPurchase',
    label: 'Cash Purchase*',
    subLabel: '(Below Deno 50)',
    width: 'w-[241px]',
  },
  {
    key: 'docAndCashPurchase',
    label: 'Doc & Cash (Purchase)*',
    subLabel: '(Deno 50 & Above)',
    width: 'w-[241px]',
  },
  { key: 'documentSales', label: 'Document (Sales)', width: 'w-[241px]' },
];

export const forexTimeOptions: SelectFieldOption[] = [
  { label: '09:30:00', value: '09:30:00' },
  { label: '12:00:00', value: '12:00:00' },
  { label: '15:00:00', value: '15:00:00' },
];

export const forexRates: ForexRate[] = [
  {
    code: 'AUD',
    name: 'Australian Dollar (AUD)',
    flag: '/images/flags/aud.svg',
    unit: 1,
    cashPurchase: 87.42,
    docAndCashPurchase: 88.15,
    documentSales: 88.94,
  },
  {
    code: 'USD',
    name: 'US Dollar (USD)',
    flag: null,
    unit: 1,
    cashPurchase: 132.65,
    docAndCashPurchase: 133.4,
    documentSales: 134.0,
  },
  {
    code: 'EUR',
    name: 'European Euro (EUR)',
    flag: null,
    unit: 1,
    cashPurchase: 154.12,
    docAndCashPurchase: 155.02,
    documentSales: 155.88,
  },
  {
    code: 'GBP',
    name: 'UK Pound Sterling (GBP)',
    flag: null,
    unit: 1,
    cashPurchase: 178.34,
    docAndCashPurchase: 179.25,
    documentSales: 180.21,
  },
  {
    code: 'CHF',
    name: 'Swiss Franc (CHF)',
    flag: null,
    unit: 1,
    cashPurchase: 162.48,
    docAndCashPurchase: 163.3,
    documentSales: 164.15,
  },
  {
    code: 'CAD',
    name: 'Canadian Dollar (CAD)',
    flag: null,
    unit: 1,
    cashPurchase: 96.71,
    docAndCashPurchase: 97.42,
    documentSales: 98.05,
  },
  {
    code: 'SGD',
    name: 'Singapore Dollar (SGD)',
    flag: null,
    unit: 1,
    cashPurchase: 101.55,
    docAndCashPurchase: 102.31,
    documentSales: 103.02,
  },
  {
    code: 'JPY',
    name: 'Japanese Yen (JPY)',
    flag: '/images/flags/japan.png',
    unit: 10,
    cashPurchase: 8.94,
    docAndCashPurchase: 9.02,
    documentSales: 9.11,
  },
  {
    code: 'CNY',
    name: 'Chinese Yuan (CNY)',
    flag: null,
    unit: 1,
    cashPurchase: 18.42,
    docAndCashPurchase: 18.61,
    documentSales: 18.79,
  },
  {
    code: 'SAR',
    name: 'Saudi Arabian Riyal (SAR)',
    flag: null,
    unit: 1,
    cashPurchase: 35.36,
    docAndCashPurchase: 35.71,
    documentSales: 36.02,
  },
  {
    code: 'QAR',
    name: 'Qatari Riyal (QAR)',
    flag: null,
    unit: 1,
    cashPurchase: 36.44,
    docAndCashPurchase: 36.81,
    documentSales: 37.14,
  },
  {
    code: 'AED',
    name: 'UAE Dirham (AED)',
    flag: null,
    unit: 1,
    cashPurchase: 36.12,
    docAndCashPurchase: 36.48,
    documentSales: 36.8,
  },
  {
    code: 'MYR',
    name: 'Malaysian Ringgit (MYR)',
    flag: null,
    unit: 1,
    cashPurchase: 31.28,
    docAndCashPurchase: 31.6,
    documentSales: 31.9,
  },
  {
    code: 'KRW',
    name: 'South Korean Won (KRW)',
    flag: null,
    unit: 100,
    cashPurchase: 9.86,
    docAndCashPurchase: 9.96,
    documentSales: 10.05,
  },
  {
    code: 'SEK',
    name: 'Swedish Kroner (SEK)',
    flag: null,
    unit: 1,
    cashPurchase: 13.71,
    docAndCashPurchase: 13.85,
    documentSales: 13.98,
  },
  {
    code: 'DKK',
    name: 'Danish Kroner (DKK)',
    flag: null,
    unit: 1,
    cashPurchase: 20.66,
    docAndCashPurchase: 20.87,
    documentSales: 21.06,
  },
  {
    code: 'HKD',
    name: 'Hong Kong Dollar (HKD)',
    flag: null,
    unit: 1,
    cashPurchase: 17.02,
    docAndCashPurchase: 17.19,
    documentSales: 17.35,
  },
  {
    code: 'THB',
    name: 'Thai Baht (THB)',
    flag: null,
    unit: 1,
    cashPurchase: 4.08,
    docAndCashPurchase: 4.12,
    documentSales: 4.16,
  },
  {
    code: 'KWD',
    name: 'Kuwaiti Dinar (KWD)',
    flag: null,
    unit: 1,
    cashPurchase: 432.18,
    docAndCashPurchase: 436.5,
    documentSales: 440.28,
  },
  {
    code: 'BHD',
    name: 'Bahraini Dinar (BHD)',
    flag: null,
    unit: 1,
    cashPurchase: 351.74,
    docAndCashPurchase: 355.26,
    documentSales: 358.34,
  },
  {
    code: 'INR',
    name: 'Indian Rupee (INR)',
    flag: null,
    unit: 100,
    cashPurchase: 160.0,
    docAndCashPurchase: 160.0,
    documentSales: 160.15,
  },
];
