export const ROUTE = {
  PERSONAL: '/',
  BUSINESS: '/business',
  SME_BANKING: '/business/sme-banking',
  REMITTANCE: '/remittance',
  PAYOUT_LOCATIONS: '/remittance/payout-locations',
  ABOUT: '/about',
  ABOUT_PROFILE: '/about/profile',
  ABOUT_CORPORATE_MISSION_AND_VISION: '/about/corporate-mission-and-vision',
  ABOUT_ORGANIZATION_STRUCTURE: '/about/organization-structure',
  ABOUT_BOARD_OF_DIRECTORS: '/about/board-of-directors',
  LOANS: '/loans',
  CARDS: '/cards',
  DEPOSIT_ACCOUNTS: '/deposit-accounts',
  SAVING_ACCOUNT: '/deposit-accounts/saving-account',
  NOTICE: '/notice',
  NEWS: '/news',
  AUCTION_NOTICE: '/auction-notice',
  FOREX_RATES: '/forex-rates',
  ATM: '/atm',
  BRANCHES: '/branches',
  SERVICES: '/services',
  TOOLS: '/services/tools',
  EMI_CALCULATOR: '/services/tools/emi-calculator',
  FD_CALCULATOR: '/services/tools/fd-calculator',
  ELIGIBILITY_CHECKER: '/services/tools/eligibility-checker',
  ADMIN: '/admin',
};
